project_id = "yrcugdepevxlbnoefnzu"

[functions.analyze-input]
verify_jwt = false

[functions.analyze-text]
verify_jwt = false

[functions.analyze-url]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false